version: "3.9"

services:
  front:
    image: sermalenk/skypro-front:lesson-34
    ports:
      - 80:80
    depends_on:
      - api

  api:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_healthy
    volumes:
      - .:/code

  migrations:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
        - .:/code
    command: python manage.py migrate

  postgres:
    image: postgres:14.6-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: todolist_postgres
    healthcheck:
      test: pg_isready -U postgres -d todolist_postgres
      interval: 3s
      timeout: 3s
      retries: 3
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: