version: "3.9"

services:
  front:
    image: sermalenk/skypro-front:lesson-35
    ports:
      - 80:80
    depends_on:
      - api

  api:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./.env:/todolist/.env

  migrations:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.env:/todolist/.env
    command: python manage.py migrate

  postgres:
    image: postgres:14.6-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 3
    volumes:
      - pg_data:/var/lib/postgresql/data


volumes:
  pg_data: